name: Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  Windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - name: Install LASlib
      run: |
        git clone https://github.com/LAStools/LAStools.git
        cd LAStools
        git checkout 29469a9f5fb1e9a6d0176ebaedcbcc474c5716f5
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=C:\Software
        cmake --build . --config Release --parallel 4
        cmake --install .
    - name: Install Geoflow
      run: |
        Invoke-WebRequest https://github.com/geoflow3d/geoflow/releases/download/v0.1.0/Geoflow-0.1.0-win64.exe -OutFile geoflow-setup.exe
        .\geoflow-setup.exe /S
    - uses: actions/checkout@v1
    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=C:\Software
        cmake --build . --target gfp_las --parallel 4 --config Release
#     - name: Install NSIS
#       run: |
#         Invoke-WebRequest https://netcologne.dl.sourceforge.net/project/nsis/NSIS%203/3.04/nsis-3.04-setup.exe -OutFile nsis-setup.exe
#         .\nsis-setup.exe /S
#     - name: Create installer
#       run: |
#         cd build
#         & "C:\Program Files\CMake\bin\cpack" -C Release --verbose
    - name: Create artifact
      uses: actions/upload-artifact@master
      with:
        name: gfp-las-win64
        path: build/Release/gfp_las.dll
